# in_ch: 3
# maxlen: 256
# embed_size: 256

gamma: -0.1
negative_slope: 0.01

ncrosses: 100
ncluster: 5000
latent_dim: 256
latent_range: 451

phi_ch: 3
phi_wh: 256
phi_steps: 50

qwh: 16
qch: 256

pathdir: /content/phi
signal_key: indices #indices #latentcode #index