# !include data.config.eyepacs.dataset

target: utils.pl.tools.dataset.DataModuleFromConfig
params:
  batch_size: 64
  num_workers: 2 #24
  train:
    target: apps.FUM.data.eyepacs.eyepacsTrain
    params:
      config:
        txt_filelist: train_filelist.txt
        SRC: pretrained_0_1DsignalOfEyepacs.zip
        N_WSTAR: -1
        S_WSTAR: '**/train/**'
        PATH_TO_CLASS_MAP:
          /1DsignalOfEyepacs/train/Grade_0: 0
          /1DsignalOfEyepacs/train/Grade_1: 1
          /1DsignalOfEyepacs/train/Grade_2: 2
          /1DsignalOfEyepacs/train/Grade_3: 3
          /1DsignalOfEyepacs/train/Grade_4: 4
        DF_NAME: train_eyepacs.csv
        DF_KEY: image_id # select row inside dataframe
        DF_VAL: dr # class value -> It can be exact one of this: int, float, str
        DF_CLASS_TYPE: int # [default: int(for classification)], float(for regression), str(for classification)
        DF_CANDIDATE:
          MAX_N_IN_CAT: 500
        MODE_VAL: 1
        EXT: npy
        SIZE: 256
        HOST_DIR: //data/external
        NAME: eyepacs_all_for_cgan
        URL:
          synset: //data/config/eyepacs/synset_human.txt
          iSynset: $5 # or we can write this -> //data/config/eyepacs/index_synset.yaml
        FILES:
          - datasetfile.zip
  validation:
    target: apps.FUM.data.eyepacs.eyepacsValidation
    params:
      config:
        txt_filelist: val_filelist.txt
        SRC: pretrained_0_1DsignalOfEyepacs.zip
        N_WSTAR: -1
        S_WSTAR: '**/val/**'
        PATH_TO_CLASS_MAP:
          /1DsignalOfEyepacs/val/Grade_0: 0
          /1DsignalOfEyepacs/val/Grade_1: 1
          /1DsignalOfEyepacs/val/Grade_2: 2
          /1DsignalOfEyepacs/val/Grade_3: 3
          /1DsignalOfEyepacs/val/Grade_4: 4
        DF_NAME: val_eyepacs.csv
        DF_KEY: image_id # select row inside dataframe
        DF_VAL: dr # class value -> It can be exact one of this: int, float, str
        DF_CLASS_TYPE: int # [default: int(for classification)], float(for regression), str(for classification)
        DF_CANDIDATE:
          MAX_N_IN_CAT: 100
        MODE_VAL: 1
        EXT: npy
        SIZE: 256
        HOST_DIR: $KAGGLE_PATH
        NAME: eyepacs_all_for_cgan
        URL:
          synset: //data/config/eyepacs/synset_human.txt
          iSynset: $5 # or insteadly we can write this -> //data/config/eyepacs/index_synset.yaml
        FILES:
          - datasetfile.zip
