net:
  params:
    forward:
      - seq0
      - Return: x
    
    seq0:
      input: x
      output: x
      head:
        - BB.Print:
            msg: -----> before
            shape: True
            input: False
        - .flatten:
            start_dim: 1
        - torch.nn.Linear:
            in_features: 16
            out_features: 6
            bias: True
        - BB.Print:
            msg: -----> after
            shape: True
            input: False