BATCH_SIZE: 4

MODEL:
  LOSS_ENTROPY_WEIGHT: 0.3
  META_LENGTH: 7

OPTIM:
  LR: 0.01
  WEIGHT_DECAY: 0.0005
  META_LR: 0.001
  META_WEIGHT_DECAY: 0.0005
  STEP_SIZE: 20

DATASET:
  NORMALIZATION_MEAN: [0.3771, 0.2320, 0.1395]
  NORMALIZATION_STD: [0.1252, 0.0857, 0.0814]
  NUM_T: 3
  NUM_IQ: 2
  NUM_M: 6
  CHANNEL_NUM: 3
