BATCH_SIZE: 8

MODEL:
  LOSS_ENTROPY_WEIGHT: 0.5
  META_LENGTH: 10

OPTIM:
  LR: 0.01
  WEIGHT_DECAY: 0.0005
  META_LR: 0.01
  META_WEIGHT_DECAY: 0.0005
  STEP_SIZE: 50

DATASET:
  NORMALIZATION_MEAN: [0.4134]
  NORMALIZATION_STD: [0.0595]
  NUM_T: 3
  NUM_IQ: 2
  NUM_M: 6
  CHANNEL_NUM: 1