BATCH_SIZE: 4
MAX_EPOCHS: 100

MODEL:
  LOSS_ENTROPY_WEIGHT: 0.2
  META_LENGTH: 5

OPTIM:
  LR: 0.01
  WEIGHT_DECAY: 0.0005
  META_LR: 0.001
  META_WEIGHT_DECAY: 0.0005
  STEP_SIZE: 25

DATASET:
  NORMALIZATION_MEAN: [0.4021, 0.2667, 0.1847]
  NORMALIZATION_STD: [0.2991, 0.2090, 0.1680]
  NUM_T: 3
  NUM_IQ: 3
  NUM_M: 9
  CHANNEL_NUM: 3