BATCH_SIZE: 8

MODEL:
  LOSS_ENTROPY_WEIGHT: 0.3
  META_LENGTH: 7

OPTIM:
  LR: 0.01
  WEIGHT_DECAY: 0.0005
  META_LR: 0.001
  META_WEIGHT_DECAY: 0.0005
  STEP_SIZE: 20

DATASET:
  NORMALIZATION_MEAN: [0.4813]
  NORMALIZATION_STD: [0.2361]
  NUM_T: 2
  NUM_IQ: 3
  NUM_M: 6
  CHANNEL_NUM: 1
