BATCH_SIZE: 4

MODEL:
  LOSS_ENTROPY_WEIGHT: 0.2
  META_LENGTH: 5

OPTIM:
  LR: 0.01
  WEIGHT_DECAY: 0.0005
  META_LR: 0.01
  META_WEIGHT_DECAY: 0.0005
  STEP_SIZE: 20

DATASET:
  NORMALIZATION_MEAN: [0.6269]
  NORMALIZATION_STD: [0.2909]
  NUM_T: 2
  NUM_IQ: 2
  NUM_M: 4
  CHANNEL_NUM: 1
