OH:
  params:
    forward:
      - seq0
      - Return: x
    
    seq0:
      input: x
      output: x
      head:
        - torch.nn.Linear:
            in_features: $in_dim
            out_features: $out_dim
            bias: True
        - torch.nn.Sigmoid
        - torch.nn.Linear:
            in_features: $out_dim
            out_features: $out_dim
            bias: True
        - torch.nn.Sigmoid
        - torch.nn.Softmax:
            dim: 1