net_step:
  forward:
    - input: [z, randn, [1, 4, 4]]  # input z
    - seq0
    - Return: LOSS_VALUE
  
  seq0:
    input:
    output: LOSS_VALUE
    head:
      - BB.Self:
          fn: net
          input: [[x, z]]
      - BB.Self:
          fn: netLoss
          input: [[y], [t]]