net_step:
  forward:
    - seq0
    - Return: LOSS_VALUE
  
  seq0:
    input:
    output: LOSS_VALUE
    head:
      - BB.Self:
          fn: OH
          input: [[x, X]]
      - BB.Self:
          fn: OHLoss
          input: [[y], [t, X]]