plot: 
  params:
    - {'space': 'time', 'label': 'x(t)', 'passive_fn': {'repeat', {repeats: 2, axis: 0}}}

Rfn: plot
signal_key: image

R_VAL: -1.0
G_VAL: 1.0

zdim: 100
nch: 16
nclass: 5
ncluster: 1024